### PR TITLE
Helpers v2.1

### PR DESCRIPTION
**Pull request by ericgaspar**
## Problem

- *Description of why you made this PR*

## Solution

- *And how do you fix that problem*

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by ericgaspar** [comment]
!testme

**Comment by ericgaspar** [comment]
!testme

**Comment by ericgaspar** [comment]
OJS doesn't seem to accept a pre-configured `config.inc.php` file... (blank page) maybe because of missing quotes around values ​​or something else

**Comment by DeMiro5001** [comment]
The install works on a test instance and I could create a journal, propose submission with a file upload.
It's ok, but it seems that I have made a lot of change in the testing branch and I can't merge the pull request to testing.
I didn't find a way to fill the install form from command line, so I think since it's running, it can be considered as beta.
I will continue to test backup and restore

**Pull request merged**
